### ISSUE TITLE
Update image from k run to dnx . run

### ISSUE THREAD

**Issue by sayedihashimi** [OmniSharp/OmniSharp.github.io#16]
We have an image for the command line case that states "k run", can we get this updated to "dnx . run"?

**Comment by Mpdreamz** [comment]
doh! updated as per:

https://github.com/OmniSharp/OmniSharp.github.io/commit/7b860602fbaf001a3e89db0cab6e50096cf56ef4

**Comment by sayedihashimi** [comment]
@mpdreamz its "dnx . run" not just "dnx run".

**Comment by Mpdreamz** [comment]
updated again, `dnx . run` feels wrong IMO will raise an issue to understand/learn why its not `dnx run` with an implied pwd and location being an optional third parameter.
