### ISSUE TITLE
Replace stock background image in hero section

### ISSUE THREAD

**Issue by peterblazejewicz** [OmniSharp/OmniSharp.github.io#39]
I think used image should be replaced or updated for at least two reasons:
- it should be easy enough to find similar stock or free image without this blurred text
- it should be optimized and not served as PNG (0.5MB thrown at user with this image alone).
Can quickly do optimization for No. 2

Thanks!

**Comment by nosami** [comment]
I quite like the image, but agree that it should be optimized. It's slow to download.

**Comment by peterblazejewicz** [comment]
@nosami Jason, I'm just not sure if it can be used as it has watermark text (that's what I meant)

I'll do PR with optimization (to JPG, progressive using imageoptim)

**Comment by nosami** [comment]
Do you mean this image? https://github.com/OmniSharp/OmniSharp.github.io/blob/88f429e1c3f957a55ee7863f0642ece1a2b65082/_site/images/header.png

I'm confused now. I can't see any watermark text (or my eyes are really bad :) )

**Comment by peterblazejewicz** [comment]
This one:
https://github.com/OmniSharp/OmniSharp.github.io/blob/88f429e1c3f957a55ee7863f0642ece1a2b65082/_site/images/team-background.png

**Comment by nosami** [comment]
OK. So we have 2 big ass images ;)

Sorry, I'm not familiar with how the site was put together :) In that case, yeah, I think we should try and source a similar image.

**Comment by peterblazejewicz** [comment]
@nosami I'm closing this as images are updated already and replacement can be done in other commit or issue! 
Thanks!
